// Generated by scripts/sign-fixture.mjs. Same content as public-key.pem.
export const PUBLIC_KEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAzsebBEuVeemRCh3AQe5NSE/jLeq9ZQ2r2DSyfndGN04=\n-----END PUBLIC KEY-----\n";
