// Generated by scripts/sign-fixture.mjs. Same content as public-key.pem.
export const PUBLIC_KEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEACSpdUHFRoNeEcqVgwy8/t49zFVVsvtPzGRLQAhBpdZI=\n-----END PUBLIC KEY-----\n";
