// Generated by scripts/sign-fixture.mjs. Same content as public-key.pem.
export const PUBLIC_KEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEABh3Te4uxyg5sqP+KMEo0VDbpoReSV/e/wsZK3flADuA=\n-----END PUBLIC KEY-----\n";
