// Signs the sample receipt once with a throwaway Ed25519 key. The private key is
// held in memory only and discarded when the process exits, so the fixture can
// never be re-signed. Re-running this script produces a NEW key and signature.
import { generateKeyPairSync, createHash, sign } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'receipts');

// Keep in sync with canonicalize() in src/lib/receipts/verify.ts (tests enforce it).
function canonicalize(v) {
  if (v === null || typeof v !== 'object') return JSON.stringify(v);
  if (Array.isArray(v)) return '[' + v.map(canonicalize).join(',') + ']';
  return '{' + Object.keys(v).sort().map((k) => JSON.stringify(k) + ':' + canonicalize(v[k])).join(',') + '}';
}

const receipt = JSON.parse(readFileSync(join(dir, 'sample-receipt.json'), 'utf8'));
const canonical = Buffer.from(canonicalize(receipt), 'utf8');
const sha256 = createHash('sha256').update(canonical).digest('hex');

const { publicKey, privateKey } = generateKeyPairSync('ed25519');
const signature = sign(null, canonical, privateKey).toString('base64');
const publicPem = publicKey.export({ type: 'spki', format: 'pem' }).toString();
const keyId = 'key_' + createHash('sha256').update(publicKey.export({ type: 'spki', format: 'der' })).digest('hex').slice(0, 12);

const fixture = {
  receipt,
  sha256,
  signature,
  signature_algorithm: 'ed25519',
  signed_at: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
  key_id: keyId,
};

writeFileSync(join(dir, 'fixture.json'), JSON.stringify(fixture, null, 2) + '\n');
writeFileSync(join(dir, 'public-key.pem'), publicPem);
// Bundler-safe copy of the same public key (the .pem is the canonical, published file).
writeFileSync(
  join(dir, 'public-key.ts'),
  `// Generated by scripts/sign-fixture.mjs. Same content as public-key.pem.\nexport const PUBLIC_KEY_PEM = ${JSON.stringify(publicPem)};\n`,
);

console.log(`Signed ${receipt.id} with ${keyId}. Private key discarded.`);
console.log(`sha256 ${sha256}`);
